module.exports = {
    PORT: 'PORT',
    MATTERMOST_SERVER: 'MATTERMOST_SERVER',
    TOKEN: 'TOKEN',
    MONGO_USERNAME: 'MONGO_USERNAME',
    MONGO_PASSWORD: 'MONGO_PASSWORD',
    MONGO_SERVER: 'MONGO_SERVER',
    CHATBOT_SERVER: 'CHATBOT_SERVER',
};
